config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  resources :sessions
  
  resources :users
  get 'welcome/index'

  resources :articles do
  	resources :comments
  	collection do
  		get :search # creates new path for search
  	end
  end

  resources :subscribers
  root  'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
	          length: {minimum: 3}
    validates :text, presence: true,	          
              length: {minimum: 2}
    
    # for photo upload
    has_attached_file :photo, styles: {large: "450x450>", thumb: "50x50#"}
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/


    # for music upload

    has_attached_file :music
    validates_attachment :music, 
    :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]},
    :file_type => {:matches => [/mp3\Z/]}


    # for movie upload
    has_attached_file :movie, :styles => 
    {
        :medium => {:geometry => "640x480", :format => 'mp4'},
        :thumb => {:geometry => "100x50", :format => 'jpg', :time => 10}
    }, :processor => [:transcoder]
    validates_attachment_content_type :movie, content_type: /\Avideo\/.*\z/



    def self.search(params)
    	articles = Article.where("text LIKE ? or title LIKE?", "%#{params[:search]}%",
    			   "%#{params[:search]}%") if params[:search].present?
    	articles # returns articles containing search words
    end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
	validates :f_name, :l_name, :email, :country,  
	presence: true
	          
    
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email


  # need to create sessions for active user & termintinting signout

  # need to Create Admin and restrict areas to only admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception


	private

	def current_user
		@current_user ||=User.find(session[:user_id]) if session[:user_id]
	end

helper_method :current_user

	def authorize
		if current_user.nil?
		redirect_to new_session_path, alert: 'Please Sign In or Sign Up!' if current_user.nil?
	end
end

	def admin_authorize
		redirect_to new_session_path, 
		alert: "Only for Admin!" unless current_user.admin 
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with name: "karthik", password: "12345", 
	# except: [:index, :show, :search]
	before_action :admin_authorize, :except => [:index, :show, :search]
	
	def index
		@articles = Article.all.reverse
	end

	def new
		@article = Article.new
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def search
		if params[:search].blank?
			@articles = Article.all
		else
			@articles = Article.search(params)
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def create
		@article = Article.new(article_params)
		if @article.save

		   redirect_to @article
	    else
		   render 'new'
	    end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end


	private

	def article_params
		params.require(:article).permit(:title, :text, :photo, :music, :video)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authorize, :only => [:create]
	before_action :admin_authorize, :only => [:destroy]

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		if @comment.save
		redirect_to article_path(@article), notice:
		"You succesfully created a Comment."
	else
		redirect_to article_path(@article), alert:
		"Comment could not be created."
	end
end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to article_path(@article)
	end

	private

	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    redirect_to root_path
  end

  def new
  end

  def create
  	user = User.find_by_userid(params[:userid])
  	if user && user.authenticate(params[:password])
  	   session[:user_id] = user.id

  	   redirect_to root_path, notice:
  	   "Welcome #{user.userid}, you succesfully Signed In!"
  	else
  		render 'new', alert:
  		"User Id and/or Password Invalid!"
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice:
    "You succesfully Logged Out!"
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

	# http_basic_authenticate_with name: "karthik", password: "12345", 
	# except: [:create]
    before_action :authorize, :except => [:create]
	before_action :admin_authorize, :except => [:index, :destroy]

	def index
		@subscribers = Subscriber.all

	end

	def create
		@subscriber = Subscriber.new(subscriber_params)

		# if email exists in databse
		if Subscriber.exists?(email: @subscriber.email)
			redirect_to root_path, 
			alert: "Sorry, that email already exists!"
		elsif
			@subscriber.save
			redirect_to root_path,			
			notice: "Thank You #{@subscriber.f_name}, for subscribing to my Newsletter!"
		else
			redirect_to root_path,
			alert: "Sorry, I failed to save your information. Please try again!"
		end
	end

	def  destroy
		@subscriber = Subscriber.find(params[:id])
		@subscriber.destroy

		redirect_to subscribers_path
	end

	private

	def subscriber_params
		params.require(:subscriber).permit(:f_name, :l_name, :email, :country)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id

			redirect_to articles_path, notice:
			"Welcome #{@user.userid}! You succesfully Created an Account."
		else
			render 'new'
		end
	end

		private

		def user_params
			params.require(:user).permit(:userid, :email, :password, :password_confirmation)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# if on active page color = white
	# if not on active page color = regular
	# argumets 'link', what page its on', 'url', 'change font color'
	def active_link_to (nav_link, contrl, action, url, style )
		if controller_name == contrl && action_name == action
			return link_to nav_link, url, id: style
		else
			return link_to nav_link, url, class: style
		end	
	end 


	#create a list of countries of world in a array.
	def your_country
		countries = ["Afghanistan",
					"Albania",
						"Algeria",
						"American Samoa",
						"Andorra",
						"Angola",
						"Anguilla"]
		countries.each do |country|
			my_country = "#{country}"
		end
		# my_country = options_for_select(['country1', 'country2', 'country3', 'country4'])
		return countries
	end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="row" style="padding-top:10%;">
	<div class="col"></div>
	<div class="col-md-7">

<h1>Edit Article!</h1>

<%= form_for @article , html: {multipart: true} do |f|%>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</p>

	<p>
		<%= f.label :text %>
		<%= f.text_area :text, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :photo %><br>
		<%= f.file_field :photo, class: 'form-control'%>
	</p>
	<p>
		<%= f.label :music %><br>
		<%= f.file_field :music, class: 'form-control'%>
	</p>
	<p>
		<%= f.label :movie %><br>
		<%= f.file_field :movie, class: 'form-control'%>
	</p>
	<p>
		<%= f.submit class: 'btn btn-lg btn-success' %>
			
	</p>
<% end%>
<p>
	<%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
	<%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary'   %>
</p>
</div>
<div class="col"></div>
</div>

app/views/articles/index.html.erb
<div class="row">
	<div class="col"></div>
	<div class="col-md-10">

<h1>List of all Articles</h1>

<% if current_user && current_user.admin? %>
<p>
	<%= link_to 'Create New Article', new_article_path, class: 'btn btn-lg btn-info'%>
</p>
<% end %>
<table class="table table-hover table-striped table-responsive-xs table-danger">
	<tr>
		<th>Photo</th>
		<th>Date</th>
		<th>Title</th>
		<th>Text</th>
		<% if current_user && current_user.admin? %>
		<th colspan="3">Editing Options</th>
		<% else %>
		<th colspan="1">Show Articles</th>
		<% end %>
    </tr>
    <% @articles.each do |article|%>

    <tr>
    	<td>
    		<% if article.photo.present?%>
    		<%= image_tag article.photo.url(:thumb)%>
    		<% else %>
    		<%= image_tag('noimage.jpg', style:"width:50px;")%>
    		<% end %>
    	</td>
    	<td>
    		<%= article.created_at.strftime('%m/%d/%Y') %>
    	</td>
    	<td>
    		<%= article.title%>
    	</td>
    	<td>
    		<%= article.text%>	
    	</td>
	    <td>
	    	<%= link_to 'Show', article_path(article), class: 'btn btn-sm btn-info' %>
	    </td>
	    <% if current_user && current_user.admin? %>
	    <td>
	    	<%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-warning'  %>
	    </td>
	    <td>
	    	<%= link_to 'Delete', article_path(article), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?'}  %>
	    </td>
	    <% end %>
	</tr>
    <% end %>
</table>

<p><%= link_to 'Home', welcome_index_path, class: 'btn btn-sm btn-primary' %></p>
</div>
<div class="col"></div>
</div>

app/views/articles/new.html.erb
<div class="row" style="padding-top:10%;">
	<div class="col"></div>
	<div class="col-md-7">

<h1>Create a New Article!</h1>

<%= form_for :article, url: articles_path, html: {multipart: true} do |f|%>

<!-- Checking for errors -->
<div class="field" style="100%;">

<% if @article.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@article.errors.count, "error")%>
		prohibited this article from being saved:
	</h2>
    <p>
    <ul>
    	<% @article.errors.full_messages.each do |msg| %>
    	<li>
    		<%= msg %>
    	</li>
    </ul>
    	<% end %>
    </p>
</div>
<% end %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</p>

	<p>
		<%= f.label :text %>
		<%= f.text_area :text, class: 'form-control' %>
	</p>
	<p>
		<%= f.label :photo %><br>
		<%= f.file_field :photo, class: 'form-control'%>
	</p>
	<p>
		<%= f.label :music %><br>
		<%= f.file_field :music, class: 'form-control'%>
	</p>
	<p>
		<%= f.label :movie %><br>
		<%= f.file_field :movie, class: 'form-control'%>
	</p>
	<p>
		<%= f.submit class: 'btn btn-lg btn-success' %>
			
	</p>
</div>
<% end %>

<p>
	<%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
	<%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary'   %>
</p>
</div>
<div class="col"></div>
</div>

app/views/articles/search.html.erb
<div class="row">
	<div class="col"></div>
	<div class="col-md-10">

<h1>List of all Articles matching your search word</h1>

<table class="table table-hover table-striped table-responsive-xs table-danger">
	<tr>
		<th>Title</th>
		<th>Text</th>
		<% if current_user && current_user.admin? %>
		<th colspan="3">Editing Options</th>
		<% else %>
		<th colspan="1">Show Articles</th>
		<% end %>
    </tr>
    <% @articles.each do |article|%>

    <tr>
    	<td>
    		<%= article.title %>
    		
    	</td>
    	<td>
    		<%= article.text %>
    			
    	</td>
	    <td>
	    	<%= link_to 'Show', article_path(article), class: 'btn btn-sm btn-info' %>
	    </td>
	    <% if current_user && current_user.admin? %>
	    <td>
	    	<%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-warning'  %>
	    </td>
	    <td>
	    	<%= link_to 'Delete', article_path(article), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?'}  %>
	    </td>
	    <% end %>
	</tr>

    <% end %>
</table>

<p><%= link_to 'Back to  all Articles', articles_path, class: 'btn btn-sm btn-primary' %></p>
</div>
<div class="col"></div>
</div>

app/views/articles/show.html.erb
<div class="row">
	<div class="col"></div>
	<div class="col-md-7">
		<% if @article.photo.present? %>
		<%= image_tag(@article.photo, style: "width:100%") %>
		<% else %>
		<%= image_tag 'banner1.jpg', style: "width:100%" %>
		<% end %>
<p><h2>TITLE</h2><br>
  <strong><%= @article.title %></strong><br>
</p>

<p>
	<%= @article.created_at.strftime('%A %-b %-d %Y | %l:%M %p') %>
</p>

<p><h3>ARTICLE</h3><br>
   <%= @article.text %>
   </p>
   <p>
   <% if @article.music.present? %>
   <%= audio_tag(@article.music, controls: true, style: "width:100%")%>
   <% end %>
</p>
<p>
   <% if @article.movie.present? %>
   <%= video_tag(@article.movie, controls: true, type: "video/mp4", style: "width:100%")%>
   <% end %>
</p>


<hr>
<%= render 'comments/comment'%>
<% if current_user %>

<hr>

<%= render 'comments/form' %>
<% else %>
Please <%= link_to 'Sign In', new_session_path %> or
<%= link_to 'Sign Up', new_user_path %> to create a comment
<% end %>
<p>
	<%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
	<%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary'   %>
</p>
</div>
<div class="col"></div>
</div>

app/views/comments/_comment.html.erb
<h2> Comments </h2>
<% @article.comments.each do |comment| %>
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<%= comment.created_at %>
</p>
<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>
<% if current_user && current_user.admin? %>
<p>
	<%= link_to 'Delete Comment', [comment.article, comment],class: 'btn btn-md btn-danger', method: :delete, data: { confirm: 'Are you sure??'}%>
</p>
<% end%>
<% end %>

app/views/comments/_form.html.erb
<!-- Form partial -->

<h4> Add Comment</h4>
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class="field" style="100%;">
<p>
	<%= f.label :commenter %><br>
	<%= f.text_field :commenter, class: 'form-control' %>
</p>
<p>
	<%= f.label :body %><br>
	<%= f.text_area :body, class: 'form-control' %>
</p>
<p>
	<%= f.submit class: 'btn btn-lg btn-success' %>
</p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KarthikBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container">
      
        <% if notice %>
        <div class="show_notice">
        <%= notice %>
        <% end %>
      </div>

      
        <% if alert %>
        <div class="show_alert">
        <%= alert %>
        <% end %>
      </div>
      
    <%= yield %>
  </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<section class="footer">

	<div class="row">
		<div class="col-md-4 darker">
			<div class="col-md-12 paddng white">
			<h4>General Info</h4>
			<hr>
			<h5 class="linktxt">Address Line 1</h5>
			<h5 class="linktxt">Address Line 2</h5>
			<h5 class="linktxt">Address Line 3</h5>
			<hr>
			<p class="small-font grey">&copy; findgovtjobs.in 2019 All Rights Reserved</p>
		</div>
		</div>
		<div class="col-md-4">
			<div class="col-md-12 paddng white">
			<h4>Subscribe</h4>
			<hr>

			<%= form_for :subscriber, url: subscribers_path do |f| %>
				<%= f.text_field :f_name, placeholder: "First Name", class: "form-control mr-sm-2 sm_style"%>
				<%= f.text_field :l_name, placeholder: "Last Name", class: "form-control mr-sm-2 sm_style"%>
	            <%= f.text_field :email, placeholder: "Your Email", class: "form-control mr-sm-2 sm_style"%>
	            <div class="form-control2 sm_style">
	            <%= f.select :country, your_country,
	                         prompt: " Select your Country"%>
	            </div>
	            <%= f.submit "Submit", class: "btn btn-light my-2 my-sm-0" %>

			<% end %>
			<!-- <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Input Your email" aria-label="Email" style="margin-bottom:10px; width:100%;"><br>
          <button class="btn btn-light my-2 my-sm-0" type="submit">Submit</button>
        </form> -->
			</div>
		</div>
		<div class="col-md-4 dark">
			<div class="col-md-12 paddng white">
			<h4>Social</h4>
			<hr>
			<h5><%= link_to 'Facebook', welcome_index_path, class: "linktxt"%></h5>
			<h5>Twitter</h5>
			<h5>Youtube</h5>
			</div>
		</div>
		
	</div>
	
</section>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Karthik The Great Artist</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= active_link_to 'Home', 'welcome', 'index', welcome_index_path, class: 'active_nav-link' %>
        </li>
        <li class="nav-item">
          <%= active_link_to 'Blog', 'articles','index', articles_path, class: 'active_nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">About</a>
        </li>
        
          <% if current_user && current_user.admin? %>

          <li class="nav-item">
            <%= active_link_to 'Subscribers', 'subscribers','index', subscribers_path, class: 'active_nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', session_path('active'), method: :delete,  class: 'active_nav-link'%>
          </li>
          <li class="nav-link">
            Hi Admin, <%= current_user.userid %>
          </li>
          <% elsif current_user %><!-- not an admin only a user-->
          <li class="nav-item">
            <%= link_to 'Sign Out', session_path('active'), method: :delete,  class: 'active_nav-link'%>
          </li>
          <li class="nav-link">
            Hi , <%= current_user.userid %>
          </li>
               <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_session_path, class: 'active_nav-link'%>
          </li>
          <li class="nav-item">
          <%= link_to 'Create Account', new_user_path, class: 'active_nav-link'%>
        </li>
        <% end%>
      </ul>
      <div class="form-inline mt-2 mt-md-0">
      <%= form_tag search_articles_path, method: :get do %>
       <%= text_field_tag :search, nil, placeholder: "Search", class: "form-control mr-sm-2" %> 
       <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0"%>
      <% end %>
    </div>
  </div>
</nav>

    

app/views/subscribers/index.html.erb
<div class="row">
    <div class="col"></div>
    <div class="col-md-10">

<h1>List of all Subscribers</h1>

<table class="table table-hover table-striped table-responsive-xs table-danger">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Country</th>
        <th>Delete</th>
    </tr>
    <% @subscribers.each do |subscriber|%>

    <tr>
        <td>
            <%= subscriber.f_name%>
        </td>
        <td>
            <%= subscriber.l_name%> 
        </td>
        <td>
            <%= subscriber.email%>
        </td>
        <td>
            <%= subscriber.country%>    
        </td>
        <td>
            <%= link_to 'Delete', subscriber_path(subscriber), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?'}  %>
        </td>

    </tr>

    <% end %>
</table>

<p><%= link_to 'Home', welcome_index_path, class: 'btn btn-sm btn-primary' %></p>
</div>
<div class="col"></div>
</div>

app/views/users/index.html.erb
<h1> users/index</h1>

app/views/users/new.html.erb
<div class="row" style="padding-top:0%;">
	<div class="col"></div>
	<div class="col-md-7">

<h1>Create an Account!</h1>

<%= form_for @user do |f| %>

<div class="field" style="100%;">

<% if @user.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@user.errors.count, "error")%>
		prohibited this user from being saved:
	</h2>
    <p>
    <ul>
    	<% @user.errors.full_messages.each do |msg| %>
    	<li>
    		<%= msg %>
    	</li>
    	<% end %>
    </ul>
    </p>
    <% if alert %>
    <%= alert %>
    <% end %>
</div>
<% end %><!-- checking errors -->
<%= f.text_field :userid, placeholder: 'Input User ID', class: 'form-control'%><br>
<%= f.email_field :email, placeholder: 'Input your email', class: 'form-control'%><br>
<%= f.password_field :password, placeholder: 'create a password', class: 'form-control'%><br>
<%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'form-control'%><br>
<%= f.submit 'Create Account'%>
<% end %>
</div>


<p>
	<%= link_to 'Articles', articles_path, class: 'btn btn-md btn-info' %>
	<%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary'   %>
</p>
</div>
<div class="col"></div>
</div>

app/views/welcome/index.html.erb
<div class="row" style="padding-top:6%;">
	<div class="col"></div>
<div class="col-md-8 text-center">
	<%= image_tag 'banner1.jpg', style: "width:100%"%>
	<div class="jumbotron">
	<h1>Welcome To My Blog</h1>
	<p><%= link_to ' Read My Blog', articles_path, class: 'btn btn-lg btn-welcome' %></p>
   </div>
</div>
<div class="col"></div>
</div>